import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Header } from '@/components/Header'
import { Box, Stack } from '@chakra-ui/react'
import { Footer } from '@/components/Footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Stack h='100%' overflowY='auto'>
            <Header />
            <Box overflowY='auto'>{children}</Box>
            <Footer />
          </Stack>
        </Providers>
      </body>
    </html>
  )
}
